---
########################
# Apply operator security standards (drop capabilities, run as non root, etc)
########################
#
# The default install of chains includes the following
# which (iiuc) works in kubernetes but not openshift.
#
#    # User 65532 is the distroless nonroot user ID
#    runAsUser: 65532
#    runAsGroup: 65532
#
# The suggested workaround is to run this command:
#   oc adm policy add-scc-to-user anyuid -z tekton-chains-controller
#
# but instead of that workaround we'll remove the runAsUser and
# runAsGroup config.
########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-chains-controller
  namespace: tekton-chains
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
        - name: tekton-chains-controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            runAsGroup:
            runAsUser:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
